# fly.toml app configuration file generated for backend-bitter-wildflower-432 on 2025-12-18T19:26:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-bitter-wildflower-432"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  processes = ["app"]

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

